version: "3.7"
services:
  devex-apollo:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongodb_container
    env_file:
      - ./.env
  devex-backend:
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - mongodb_container
    env_file:
      - ./backend/.env
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCUMENTDB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCUMENTDB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container2:/data/db

volumes:
  mongodb_data_container2:
