version: "3.7"
services:
  devex-apollo:
    build: .
    ports:
      - 5001:5000
    depends_on:
      - mongodb_container
    env_file:
      - ./prod.env
  devex-backend:
    build: ./backend
    ports:
      - 3002:3000
    depends_on:
      - mongodb_container
    env_file:
      - ./backend/prod.env
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCUMENTDB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCUMENTDB_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
